spring.application.name=lets-play
# Clé secrète twila w secure ( provide 256-bit at least )
jwt.secret=LetsPlaySecretKeyThatIsVeryLongAndSecureForJWT2026!

# Expiration dyal token (1 nahr = 86400000 millisecondes)
jwt.expiration=86400000